logging:
  level:
    root: INFO

---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: DEBUG

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  path: '/tmp/'
  file: readinglist.log
  level:
    root: WARN
