logging:
  level:
    root: INFO

---

spring:
  profiles: dev

logging:
  level:
    root: DEBUG

---

spring:
  profiles: prod

logging:
  path: '/tmp/'
  file: readinglist.log
  level:
    root: WARN
